/*
    Generated by Atomist on 05 07 2016 
*/
package com.jackietreehornpublishing;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MycoolaggregateApplication {

    public static void main(String[] args) {
        SpringApplication.run(MycoolaggregateApplication.class, args);
    }
}
